// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f4c25750-c03f-4df2-a0ac-1dffef7e0cf4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Tw7GqaHoF",
    "aws_user_pools_web_client_id": "51p136bpmj3t0gk1t0to5uf9kd",
    "aws_user_files_s3_bucket": "testc10ff86ded7c4e41941b42615c337b02",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
